
function for_all ()

% function created textfiles for Maxvalue in ROI, zum Ausrechnen des LI's


    ControlsFolder = '/media/truecrypt7/kirsten_thesis/data/controls/';

    DIR = dir (ControlsFolder)
    isub = [DIR(:).isdir]; %  returns logical vector
    nameFolds = {DIR(isub).name}';
    nameFolds(ismember(nameFolds,{'.','..'})) = [];
    Table=[];

    for i= 1:size(nameFolds)
   
      
   [Table]=findextrema(strcat(ControlsFolder, filesep, nameFolds{i,1}), nameFolds{i}, Table, i, 'Verbgeneration')  
    
    end

    Path=strcat('/media/truecrypt7/kirsten_thesis/data/patients/','Extrema_and_Locations_controls_Verbgeneration.mat')
    save(Path, 'Table')
    
end


function [Table]=findextrema(SubjectPath, SubjectName, Table, i, Task)

PathMask_complete = strcat ('/home/kh/ShareWindows/Masks_fMRI/Brainmask+tlrc');
PathMask_left = strcat ('/home/kh/ShareWindows/Masks_fMRI/Left_Brainmask+tlrc');
PathMask_right = strcat ('/home/kh/ShareWindows/Masks_fMRI/Right_Brainmask+tlrc');

Path=strcat(SubjectPath, filesep, 'fMRI/statistics/', Task);

cd(Path)

!3dcopy wspmT_0001.hdr wspmT_0001

 eval(['!3dresample -master ', PathMask_complete, ' -prefix ', ' wspmT_0001_downsampled', ' -inset ', 'wspmT_0001+tlrc' ]) 
 !3dcopy wspmT_0001_downsampled+tlrc wspmT_0001_downsampled.nii
 
 if 1==strcmp(SubjectName, 'Pat_01_13021km') || 1==strcmp(SubjectName, 'Pat_21_13056hz') % df=158
    eval(['!3dcalc -a wspmT_0001_downsampled+tlrc  -exp ''fitt_t2z(a, 158)'' -prefix wspmT_0001_downsampled_z_transf'])  
 elseif  1==strcmp(SubjectName, 'zzz_sf') % df=118
    eval(['!3dcalc -a wspmT_0001_downsampled+tlrc  -exp ''fitt_t2z(a, 118)'' -prefix wspmT_0001_downsampled_z_transf'])  
 else
     eval(['!3dcalc -a wspmT_0001_downsampled+tlrc  -exp ''fitt_t2z(a, 198)'' -prefix wspmT_0001_downsampled_z_transf'])  
 end
 
    eval(['!3dExtrema -volume -mask_file ', PathMask_complete, ' wspmT_0001_downsampled_z_transf+tlrc > Extrema_Mask_complete.txt'])
        eval(['!3dExtrema -volume -mask_file ', PathMask_left, ' wspmT_0001_downsampled_z_transf+tlrc > Extrema_left_Brain.txt'])
            eval(['!3dExtrema -volume -mask_file ', PathMask_right, ' wspmT_0001_downsampled_z_transf+tlrc > Extrema_right_Brain.txt'])

[Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, 'Mask_complete', 1)
[Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, 'left_Brain', 2)
[Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, 'right_Brain', 3)

end


function [Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, Mask, A)

[newData1]=importfile (strcat('Extrema_', Mask, '.txt'))

if 0==isstruct(newData1) %kh, Patient18 hat no extreme values
    Table.(Mask).Location{i,1} = 'subject has no extreme Value';
    Table.(Mask).Coord(i,1:4)  = [NaN NaN NaN NaN]
    return
end

eval(['!whereami ', num2str(newData1.data(1,3)),' ', num2str(newData1.data(1,4)),' ', num2str(newData1.data(1,5)), ' > Whereami_' Mask,'.txt' ])

fid = fopen(strcat('Whereami_',Mask, '.txt'));
Whereami=textscan(fid, '%s', 'delimiter', sprintf('\f'));
fclose(fid)

Number=strfind( Whereami{1,1}, 'Atlas CA_ML_18_MNIA: Macro Labels (N27)')
for j=1:length(Number)
    X(j)=~isempty(Number{j})
end

  X=double(X)
[row]=find(X==1)

Table.(Mask).Location{i,1} = Whereami{1,1}{row+1}
Table.(Mask).Coord(i,1:4)  = newData1.data(1,2:5)

end


function [newData1]=importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-May-2014 16:09:09

DELIMITER = ' ';
HEADERLINES = 10;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
if 0==isstruct(newData1) %kh, Patient18 hat no extreme values 
    return
end

vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

end