function patients ()
   
PatientFolder = '/media/truecrypt7/kirsten_thesis/data/patients/';
ControlsFolder = '/media/truecrypt7/kirsten_thesis/data/controls/';

for_all (PatientFolder, 'Patients', 'Verbgeneration')
for_all (ControlsFolder, 'Controls', 'Verbgeneration')

end

function for_all (Folder, group, Task)

    
    DIR = dir (Folder)
    isub = [DIR(:).isdir]; %  returns logical vector
    nameFolds = {DIR(isub).name}';
    nameFolds(ismember(nameFolds,{'.','..'})) = [];
    Table=[];

    for i= 1:size(nameFolds)
   
   [Table]=findextrema(strcat(Folder, filesep, nameFolds{i,1}), nameFolds{i}, Table, i, Task)  
   
    end

    Path=strcat('/home/kh/ShareWindows/data/Extrema_and_Locations_', group, '_', Task, '_fMRI_downs_ROIs.mat')
    save(Path, 'Table')
    
end


function [Table]=findextrema(SubjectPath, SubjectName, Table, i, Task)

PathMask = strcat ('/home/kh/ShareWindows/data/patients/ROIs_complete_MEG+tlrc');


Path=strcat(SubjectPath, filesep, 'fMRI/statistics/', Task);

cd(Path)
 
    eval(['!3dExtrema -volume -average -mask_file ', PathMask, ' wspmT_0001_downsampled_z_transf+tlrc > Extrema_ROI_complete.txt'])
       

[Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, 'ROI_complete', 1)


end


function [Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, Mask, A)

[newData1]=importfile (strcat('Extrema_', Mask, '.txt'))

if 0==isstruct(newData1) %kh, Patient18 hat no extreme values
    Table.(Mask).Location{i,1} = 'subject has no extreme Value';
    Table.(Mask).Coord(i,1:4)  = [NaN NaN NaN NaN];
    return
end

eval(['!whereami ', num2str(newData1.data(1,3)),' ', num2str(newData1.data(1,4)),' ', num2str(newData1.data(1,5)), ' > Whereami_' Mask,'.txt' ])

fid = fopen(strcat('Whereami_',Mask, '.txt'));
Whereami=textscan(fid, '%s', 'delimiter', sprintf('\f'));
fclose(fid)

Number=strfind( Whereami{1,1}, 'Atlas CA_ML_18_MNIA: Macro Labels (N27)')
for j=1:length(Number)
    X(j)=~isempty(Number{j})
end

  X=double(X)
[row]=find(X==1)

Table.(Mask).Location{i,1} = Whereami{1,1}{row+1};
Table.(Mask).Coord(i,1:4)  = newData1.data(1,2:5);

end


function [newData1]=importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-May-2014 16:09:09

DELIMITER = ' ';
HEADERLINES = 10;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
if 0==isstruct(newData1) %kh, Patient18 hat no extreme values 
    return
end

vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

end