function patients ()
   
PatientFolder = '/home/kh/ShareWindows/data/patients/patients_SAM/';
ControlsFolder = '/home/kh/ShareWindows/data/controls/controls_SAM/';

for_all (PatientFolder, 'Patients')
for_all (ControlsFolder, 'Controls')

end


function for_all (Folder, group)


    DIR = dir (Folder)
    isub = [DIR(:).isdir]; %  returns logical vector
    nameFolds = {DIR(isub).name}';
    nameFolds(ismember(nameFolds,{'.','..'})) = [];
    Table=[];

    for i= 1:size(nameFolds)
   

    TimeInt = [.32, .6];
      
   [Table]=findextrema(strcat(Folder, filesep, nameFolds{i,1}), nameFolds{i}, Table, i, group)  
    
    end

    Path=strcat('/home/kh/ShareWindows/data', filesep, 'Extrema_and_Locations_', group,'_ROIs_MEG.mat')
    save(Path, 'Table')
    
end


function [Table]=findextrema(SubjectPath, SubjectName, Table, i, group)

if 1==strcmp(SubjectName,'Pat_02_13008rh_1') || 1==strcmp(SubjectName,'Pat_02_13008rh_2') || 1==strcmp(SubjectName,'Pat_03_13014bg_1') || 1==strcmp(SubjectName,'Pat_03_13014bg_2')

    return
end

if 1==strcmp(group, 'Patients')
    Path=strcat(SubjectPath, filesep, 'TimeIntervalls');
else 
    Path=strcat(SubjectPath, filesep, 'SAM');
end
cd(Path)


% !3dcalc -a Broca_left_dil+tlrc -b Broca_right_dil+tlrc -c Wernicke_left_dil+tlrc -d Wernicke_right_dil+tlrc -expr 'a+b+c+d' -prefix ROIs_complete_MEG

PathMask = strcat ('/home/kh/ShareWindows/data/patients/ROIs_complete_MEG+tlrc');


if 1==strcmp (SubjectName,'Pat_02_13008rh') ||  1==strcmp (SubjectName,'Pat_03_13014bg')
    eval(['!3dExtrema -volume -mask_file ', PathMask, ' BothRuns_br_z_transf_brain01ERF_noise_0.32-0.6s+tlrc > Extrema_ROIs_complete.txt'])
    
elseif 1==strcmp(group, 'Patients')
    
    eval(['!3dExtrema -volume -average -mask_file ', PathMask, ' br_z_transf_brain01ERF_noise_0.32-0.6s_', SubjectName,'+tlrc > Extrema_ROIs_complete.txt'])
else
    eval(['!3dExtrema -volume -average -mask_file ', PathMask, ' br_z_transf_brain01ERF_0.32-0.6s_', SubjectName,'+tlrc > Extrema_ROIs_complete.txt'])
    
end

[Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, 'ROIs_complete', 1)

end


function [Table, Mask]=kh_Whereami (SubjectPath, SubjectName, Table, i, Mask, A)

[newData1]=importfile (strcat('Extrema_', Mask, '.txt'))

if 0==isstruct(newData1) %kh, Patient18 hat no extreme values
    Table.(Mask).Location{i,1} = 'subject has no extreme Value';
    Table.(Mask).Coord(i,1:4)  = [NaN NaN NaN NaN]
    return
end

eval(['!whereami ', num2str(newData1.data(1,3)),' ', num2str(newData1.data(1,4)),' ', num2str(newData1.data(1,5)), ' > Whereami_' Mask,'.txt' ])

fid = fopen(strcat('Whereami_',Mask, '.txt'));
Whereami=textscan(fid, '%s', 'delimiter', sprintf('\f'));
fclose(fid)

Number=strfind( Whereami{1,1}, 'Atlas CA_ML_18_MNIA: Macro Labels (N27)')
for j=1:length(Number)
    X(j)=~isempty(Number{j})
end

  X=double(X)
[row]=find(X==1)

Table.(Mask).Location{i,1} = Whereami{1,1}{row+1}
Table.(Mask).Coord(i,1:4)  = newData1.data(1,2:5)

end



function [newData1]=importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-May-2014 16:09:09

DELIMITER = ' ';
HEADERLINES = 10;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
if 0==isstruct(newData1) %kh, Patient18 hat no extreme values 
    return
end

vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

end